version: "2"
checks:
  argument-count:
    config:
      threshold: 6
  complex-logic:
    config:
      threshold: 4
  file-lines:
    config:
      threshold: 300
  method-complexity:
    config:
      threshold: 8
  method-count:
    config:
      threshold: 20
  method-lines:
    config:
      threshold: 30
  nested-control-flow:
    config:
      threshold: 5
  return-statements:
    config:
      threshold: 8
