# # # # # # # # # # # # # # # # # # # # #
#        GetMeHome Configuration        #
# https://github.com/SimonOrJ/GetMeHome #


###                   ###
# Home storage settings #
storage:
#                       #

# type - Format to save homes as. Possible values:
# YAML    Save it as homes.yml file. Good for small servers.
# SQLite  Save it as homes.db file.
# MySQL   Save it on a MySQL database. Ideal for huge player base.
    type: YAML
  
# YAML-only:
# savename - should the plugin save player names with their UUID?
#            This is only for you to see and know.
    savename: true
  
# MySQL-only:
    database: minecraft
    username: username
    password: password

# MySQL or SQLite:
    prefix: gmh_


###          ###
# Localization #
localization:
#              #

# Most of these should be self-explanatory.
# Tag to prefix before any message.
    TAG: "&6[GetMeHome]"

# Maximum distance for "Welcome to your home" message to not show
    HOME_WELCOME_DIST: 4;

# Home command messages
# Use {0} in place of home name(s).
    HOME: "&eWelcome to your &f{0}&e home."
    SET: "&f{0}&e home set."
    DELETE: "&7{0}&e has been deleted."
    DNE: "&7{0}&e home is not set."
# Listing homes
    LIST: "&eYour home:"
    LIST_PLURAL: "&eYour homes:"
    LIST_HOME_COLOR: "&a"
    NOHOME: "&eYou are homeless!"
# Error handling
# Use {0} in place of home limit.
    LIMIT_REACHED: "&eYou are at your limit of &c{0}&e home(s)."
    ERROR: "&cAn error has occurred."


###         ###
# Home Limits #
limit:
#             #

# default - default home limit. 1 means only home named "default"
#           is allowed.  This must be on top. (leave it here)
    default: 1
# The checking priority goes from top to bottom (excluding default).
#   If a person has two or more permission groups in the list below,
#   the top-most node will have priority.
# The rest of the home limit can be listed in this format:
#   permission.node: maximum number of homes
# example:
    gmh.twohomes: 2
