# GetMeHome by Simon Chuu

# For help, follow the plugin project link below:
# https://github.com/SimonOrJ/GetMeHome/

# TODO: Rewrite the configuration
storage:
  # type - Format to save homes as. Possible values:
  # YAML    Good enough for small servers.
  # MySQL   Ideal for huge player base.
  type: YAML
  
  # YAML:
  # should the plugin save player names with their UUID?
  # This is only for your reference when looking through the file.
  savename: true
  
  # For MySQL.
  # Also, if planning on migrating to MySQL, fill this in.
  hostname: localhost:3306
  database: minecraft
  username: username
  password: password
  prefix: gmh_

formatting:
  # Accepts only color (0-9,a-f)
  color: e
  italic: false
  bold: false
  underline: false

# Maximum distance away from home point for "Welcome home" message to not show on /home
welcomeHomeRadius: 4;

limit:
  # default - default home limit. If removed, defaults to 1.
  default: 1

  # The rest of the home limit can be listed in this format:
  #   permission.node: maximum number of homes
  ### Permission on top of this list will be checked first! ###
  gmh.twohomes: 2

# Enable metrics for this plugin? (If unsure, leave it as true)
#   Link to metrics: https://bstats.org/plugin/bukkit/GetMeHome/
enable-metrics: true
