# GetMeHome by Simon Chuu

# For help, follow the plugin project link below:
# https://github.com/SimonOrJ/GetMeHome/

# Storage settings
storage:
  # should the plugin save player names with their UUID?
  # This is only for your reference when looking through the file.
  savename: true

message:
  # Prefix for beginning of message. Use &[0-9a-f] to set colors.
  prefix: "&6[GetMeHome]"
  # Colors: Accepted values are 0~9 or a~f.
  # https://minecraft.gamepedia.com/Formatting_codes
  content-color: e
  # Color for the focus points. e.g. home names or player names
  focus-color: f

# Maximum distance away from home point for "Welcome home" message to not show
# on /home
#   Set to -1 to disable "Welcome home" message
welcome-home-radius: 4

# Home limits (based on custom permission nodes)
# Set to -1 for unlimited homes
limit:
  # default - default home limit. If removed, defaults to 1.
  default: 1

  # The rest of the home limit can be listed in this format:
  #   permission.node: maximum number of homes
  ### Permission on top of this list will be checked first! ###
  getmehome.op: -1
  getmehome.twohomes: 2



# Home warm-up in ticks (based on custom permission nodes)
# 20 ticks = 1 second
warmup:
  # default - default warm-up time. If removed, defaults to 0.
  default: 0

  # The rest of the warm up time can be listed in this format:
  #   permission.node: warm up time in ticks
  ### Permission on top of this list will be checked first! ###
  getmehome.op: 0
  getmehome.warmup5s: 100



# Enable metrics for this plugin? (If unsure, leave it as true)
#   Link to metrics: https://bstats.org/plugin/bukkit/GetMeHome/
enable-metrics: true
