name: GetMeHome
version: ${project.version}
author: SimonOrJ
description: Simple home plugin that just gets you home
main: com.simonorj.mc.getmehome.GetMeHome
website: http://github.com/SimonOrJ/GetMeHome

commands:
  getmehome:
    description: GetMeHome's main (help) command
    usage: /getmehome [reload|migrate]
  home:
    aliases: [h]
    description: Sends you home
    usage: /home [home name]
  sethome:
    description: Sets home at your current position
    usage: /sethome [home name]
  setdefaulthome:
    aliases: [defaulthome]
    description: Sets a home name as a default home.
    usage: /setdefaulthome <home name>
  delhome:
    description: Delets a set home
    usage: /delhome [home name]
  listhomes:
    description: Lists all the homes
    usage: /listhomes

permissions:
  getmehome.reload:
    description: Allows /getmehome reload
    default: op
  getmehome.migrate:
    description: Allows /getmehome migrate
    default: op
  getmehome.listother:
    description: Allows /listhomes <player> (as opposed to just /listhomes)
    default: op
  getmehome.*:
    description: Allows all admin commands
    children:
      getmehome.reload: true
      getmehome.migrate: true
      getmehome.otherhome: true
