name: GetMeHome
version: ${project.version}
author: SimonOrJ
description: Simple home plugin that just gets you home. Nothing more.
main: com.simonorj.mc.getmehome.HereIsYourHome
website: http://github.com/SimonOrJ/GetMeHome

commands:
  home:
    aliases: [h]
    description: Sends you home
    usage: /home [home name]
  sethome:
    aliases: [seth]
    description: Sets home at your current position
    usage: /sethome [home name]
  listhomes:
    aliases: [listhome,listh]
    description: Lists all the homes you have
    usage: /listhomes

permissions:
  getmehome.admin:
    description: this player can /kill others.
    default: op
