name: GetMeHome
version: ${project.version}
author: SimonOrJ
description: Simple home plugin that just gets you home. Nothing more.
main: com.simonorj.mc.getmehome.HereIsYourHome
website: http://github.com/SimonOrJ/GetMeHome

commands:
  gmh:
    description: GetMeHome's main (help) command
  home:
    aliases: [h]
    description: Sends you home
    usage: /home [home name]
  sethome:
    aliases: [seth, homeset]
    description: Sets home at your current position
    usage: /sethome [home name]
  deletehome:
    aliases: [deleteh, delhome, delh, homedelete, homed]
    description: Delets a set home
    usage: /delhome [home name]
  listhomes:
    aliases: [listhome, listh, homelist, homel, homes]
    description: Lists all the homes you have
    usage: /listhomes

permissions:
  getmehome.admin:
    description: this player can /kill others.
    default: op
