name: GetMeHome
version: ${project.version}
author: Simon Chuu
description: Simple home plugin that just gets you home
main: com.simonorj.mc.getmehome.GetMeHome
website: http://github.com/SimonOrJ/GetMeHome

commands:
  getmehome:
    description: GetMeHome's main (help) command
    usage: /getmehome
  delhome:
    description: Delets a set home
    usage: /delhome [home name]
    permission: getmehome.command.delhome
  home:
    aliases: [h]
    description: Sends you home
    usage: /home [home name]
    permission: getmehome.command.home
  listhomes:
    aliases: [homes]
    description: Lists all the homes
    usage: /listhomes
    permission: getmehome.command.listhomes
  sethome:
    description: Sets home at your current position
    usage: /sethome [home name]
    permission: getmehome.command.sethome
  setdefaulthome:
    description: Sets a different home name as the default home.
    usage: /setdefaulthome <home name>
    permission: getmehome.command.setdefaulthome

permissions:
  getmehome.reload:
    description: Allows /getmehome reload
    default: op
  getmehome.user:
    description: Allows the user-level usage of home commands
    default: true
    children:
      getmehome.command.delhome: true
      getmehome.command.home: true
      getmehome.command.listhomes: true
      getmehome.command.sethome: true
      getmehome.command.setdefaulthome: true
  getmehome.command.delhome:
    description: Allows /delhome
    default: true
  getmehome.command.home:
    description: Allows /home
    default: true
  getmehome.command.home.other:
    description: Allows `/home <player> <home>` to teleport to other user's homes
    default: op
    children:
      getmehome.command.home: true
  getmehome.command.listhomes:
    description: Allows /listhomes
    default: true
  getmehome.command.listhomes.other:
    description: Allows `/listhomes <player>` (as opposed to just /listhomes)
    default: op
    children:
      getmehome.command.listhomes: true
  getmehome.command.sethome:
    description: Allows /sethome
    default: true
  getmehome.command.setdefaulthome:
    description: Allows /setdefaulthome
    default: true
